[project]
name = "lists-of-tasks"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.22.0",
    "aiohttp-socks>=0.11.0",
    "apscheduler>=3.11.2",
    "dotenv>=0.9.9",
    "google-auth>=2.47.0",
    "gspread>=6.2.1",
    "ruff>=0.14.10",
    "sqlalchemy>=2.0.49",
]
[dependency-groups]
dev = [
    "ruff>=0.12.7",
]


[tool.ruff]
lint.select = [
  "ANN",  # Проверка аннотаций типов (type hints) — требуют указывать типы у аргументов, возвращаемых значений и т.д.
  "UP",   # Проверка устаревших конструкций и импортов — обновляет старый синтаксис (pyupgrade)
  "F",    # Проверка синтаксических ошибок и потенциальных багов — неиспользуемые переменные, ошибки в логике (из Pyflakes)
  "E",    # Проверка соответствия PEP8 (ошибки форматирования) — например, отступы, пробелы
  "W",    # Предупреждения по стилю (Warnings) — например, пробел перед скобками, пустые блоки кода и т.п.
]
line-length = 120
# включаем автоисправление
#fix = true