from typing import Protocol, runtime_checkable

from domain.tasks import Task


@runtime_checkable
class ITaskRepository(Protocol):
    def get_by_id(self, task_id: int) -> Task | None: ...
    def save(self, task: Task) -> Task: ...
    def all(self) -> list[Task]: ...
    def delete(self, task_id: int) -> None: ...
