from typing import Protocol, runtime_checkable

from domain.users import User


# =============================================
# Чистый интерфейс репозитория
# =============================================

@runtime_checkable
class IUserRepository(Protocol):
    def get_by_id(self, user_id: int) -> User | None: ...
    def get_by_username(self, username: str) -> User | None: ...
    def save(self, user: User) -> User: ...
    def all(self) -> list[User]: ...
    def delete(self, user_id: int) -> None: ...
    def delete_list(self, user_id: int, list_id: int) -> bool: ...
    def delete_task(self, user_id: int, task_id: int) -> bool: ...
    def reset_all_tasks(self) -> dict[int, list[dict]]: ...
